version: '3.8'

services:
  vaultsecure:
    build:
      context: .
      dockerfile: Dockerfile
    image: vaultsecure-gallery:latest
    container_name: vaultsecure-gallery
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # Persist image uploads
      - gallery_images:/app/backend/images/gallery
      # Persist logs
      - logs:/var/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - vaultsecure
    labels:
      - "com.docker.compose.project=vaultsecure"
      - "description=VaultSecure Gallery - Secure Image Gallery with Screenshot Protection"

volumes:
  gallery_images:
    driver: local
  logs:
    driver: local

networks:
  vaultsecure:
    driver: bridge
    name: vaultsecure-network
